### ISSUE TITLE
demean user interface is unintuitive

### ISSUE THREAD

**Issue by japhir** [mingsongli/acycle#12]
Many students struggled to understand the UI of the demean dialog box.

We've worked out that the correct procedure to get output is:
1. select series
2. click demean option from menu
3. mark one or more of the boxes of the analyses (LOESS, demean, linear etc.) you want to do
4. click OK
5. inspect plot
6. select the analysis you want to save from the dropdown menu to save the output

This last step is confusing, people seem to expect that when you click OK the output will be saved. If you select multiple, I think it should just save all versions separately upon clicking OK or perhaps change the word in the OK dialog to something like Plot.

version info omitted since this is the same for all versions we've seen

**Comment by mingsongli** [comment]
Please try Acycle v2.1. "OK" button was revised to "Plot". 

https://github.com/mingsongli/acycle
