### ISSUE TITLE
Add option to plot spectra as a function of period in stead of/in addition to frequency or add period on point click hover info

### ISSUE THREAD

**Issue by japhir** [mingsongli/acycle#14]
Many students are interested in the periods of their spectral peaks. Plotting against frequency is common, but it may be nice to add one of several suggestions below:
- add an option to plot against period in stead of frequency (most people would be agains this, however)
- add an option for a secondary x-axis above, with the period info. This would be a non-linear axis though
- when you click any of the points/peaks in a spectrum, show the period in addition to the x- and y-values

**Comment by mingsongli** [comment]
Please try Acycle v2.1. All included.
