### ISSUE TITLE
When changing the bandpass filter settings, the plots don't zoom consistently

### ISSUE THREAD

**Issue by japhir** [mingsongli/acycle#16]
1. select data
2. filter
3. change one of minimum or peak centre
- the top plot (the Lomb-Scaigle (how do you write that?) changes the frequency axis accordingly
- but the mtm spectrum doesn't change along with it.

this was on a chinese windows 10 computer, running with the matlab runtime. I'm not sure which versions of either were installed.

**Comment by mingsongli** [comment]
Acycle v2.1 includes updated Filtering GUI, which shows the frequency response using given parameters (frequency, bandwidth, etc.)
