### ISSUE TITLE
Bug: Unnecessary data generate in the bootstp file

### ISSUE THREAD

**Issue by GeoFengCheng** [mingsongli/acycle#19]
After clicking the bootstrap button, two files (bootstrap and percentile) are then generated. In each file, multiple column datasets are then generated. Some of them seem to be unnecessary.

**Comment by mingsongli** [comment]
The tool of "Math - Smooth - Bootstrap" in Acycle v2.1.1 (and future versions) will adjust the data saving style to fit our expectation.

*_bootstp_meanstd.txt includes 6 columns of data:
[time, mean-2*std, mean-std, mean, mean+std, mean+2*std], that is, 2 sigma, 1 sigma, and mean values.

*_bootstp_percentile.txt includes 8 columns of data:
[time, percentiles of [0.5,2.5,5,25,50,75,95,97.5,99.5]], that is, 99%, 95%, 90%, and 50% confidence intervals, and median values.
