### ISSUE TITLE
Several errors on one machine (due to lack of toolbox?): document required toolboxes

### ISSUE THREAD

**Issue by japhir** [mingsongli/acycle#8]
Hi! Here are the first bugs that a student experienced. It looks like in this case it's the lack of the Signal Processing Toolbox.

Running spectral analysis doesn't work:
1. make basic series ETP La2004 1--1000 (works)
2. run mtm on series
output of matlab command line:
```
Error in redconfML (line 69)
[pxx,f] = pmtm(x,nw,nfft);

Error in spectrum>pushbutton17_Callback (line 889)
                [rhoM,
s0M,redconfAR1,redconfML96]=redconfML(datax,dt,nw,nzeropad,linlog,smoothwin,fmax,1);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in spectrum (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)spectrum('pushbutton17_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating UIControl Callback.
```

Creating insolation series doesn't work:
1. make basic series insolation daily La2004 1--1000
warning dialog:
` Check time scale input, t must be larger than 0 and less than 249000 ka`
no error messages

ESA/wavelet both work as expected

Age scale results in empty plot in stead of dialog box when only age model is selected
1. click age scale
2. select an age model, but not a depth series
3. click ok
empty plot, following error messages on command line
```
Error using load
File name is empty.

Error in agescale>pushbutton8_Callback (line 303)
    data = load(data_name);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in agescale (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)agescale('pushbutton8_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating UIControl Callback.

Error using load
File name is empty.

Error in agescale>pushbutton8_Callback (line 303)
    data = load(data_name);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in agescale (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)agescale('pushbutton8_Callback',hObject,eventdata,guidata(hObject))

Error while evaluating UIControl Callback.
```

This student has:
windows 10
matlab 9.7 R2019b
matlab toolboxes: 
  - simulink 10.0
  - statistics and machine learning toolbox 11.6
  - symbolic math toolbox 8.4
acycle v1.4

I will update when the student manages to install the `Signal Processing Toolbox` :).

**Comment by mingsongli** [comment]
Thanks for this bug report. 

**Here is the full list of 9 toolboxes that _Acycle_ MATLAB version v2.0 will need:**

```
'Signal Processing Toolbox'
'Statistics and Machine Learning Toolbox'
'Image Processing Toolbox'
'Fuzzy Logic Toolbox'
'Curve Fitting Toolbox'
'Parallel Computing Toolbox'
'MATLAB Parallel Server'
'Polyspace Bug Finder'
'Wavelet Toolbox'
```

Please install these toolboxes for your Matlab to ensure _Acycle_ Matlab version works as expected.

Feb. 21, 2020

**Comment by japhir** [comment]
Hi @mingsongli! I was asked to quickly write up how to install the software for another course. I was very happy to just link to the great new wiki page, but didn't see which toolboxes are required in the installation guide. Could you add these requirements there perhaps? :)

**Comment by mingsongli** [comment]
Hi Ilja,&nbsp;
Sorry for the late reply. I didn't update the wiki page for a while. Will update it in the future.
Now the information you expected can be found in the user guide section "3.3.1 Toolboxes" https://github.com/mingsongli/acycle/tree/master/doc
Cheers,
Mingsong

&nbsp;

Mingsong


--------
Mingsong Li
Postdoc,&nbsp;Penn State University

410 Deike Bldg, University Park, PA 16802

mul450@psu.edu; limingsonglms@gmail.com

www.mingsongli.com


 


&nbsp;




------------------&nbsp;Original&nbsp;------------------
