### ISSUE TITLE
Default options override not set permanently in dialog boxes (e.g. in insolation)

### ISSUE THREAD

**Issue by japhir** [mingsongli/acycle#9]
1. create insolation time series
2. change one of the default options and click ok
3. create a new insolation series
- options still show the previously changed values (this is expected)
- but results are not using those values but return to the defaults!
(e.g. change 65 degrees to 25, make the series, then click insolation again, it says 25 but generates 65 when you click ok).

This error occurred with all students! And apparently not only with insolation.

but here is the info for the student who helped me report it:
windows 10
matlab 9.7 R2019b
matlab toolboxes: 
  - simulink 10.0
  - statistics and machine learning toolbox 11.6
  - symbolic math toolbox 8.4
acycle v1.4

**Comment by mingsongli** [comment]
**Starting from Acycle v2.1, the Insolation GUI will restore all default values when users click the menu for this tool.** 

Please do let me know if there are any other similar bugs.
